import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
// import App from './App';
import AppRouter from './AppRouter';
import * as serviceWorker from './serviceWorker';
// console.log(RouterClass);
// ReactDOM.render(<App/>, document.getElementById('root'));
ReactDOM.render(<AppRouter/>, document.getElementById('root'));
serviceWorker.unregister();
